[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7.0" }
shared = { path = "../shared" }
bevy_renet = "0.0.2"
bincode = "1.3.1"
serde = { version = "1.0.117", features = [ "derive" ] } 