[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7.0", default-features = false }
shared = { path = "../shared" }
bevy-inspector-egui = "0.11.0"

[[bin]]
name = "server"
path = "src/server_main.rs"