[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7.0" }
naia-bevy-shared = "0.10.1"
naia-shared = "0.10.0"
log = { version = "0.4" }
naia-derive = { version = "0.10" }
naia-serde = { version = "0.10" }