[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7.0", default-features=false }
naia-shared = "0.10.0"
cfg-if = { version = "1.0" }
log = { version = "0.4" }